/**
 * Builds the exact Direct Orange PG Initiate Sale JSON request body,
 * including the computed secureHash, from server-resolved transaction
 * data and server-side config. Pure and deterministic given its inputs
 * (merchantTxnNo/txnDate are generated by the caller, not here, so this
 * function never needs to touch the clock or a random source itself).
 */

import {
  generateIciciDirectOrangeInitiateSaleHash,
  type IciciDirectOrangeInitiateSaleFields,
} from './crypto.js';
import type { IciciConfig } from './env.js';

/** Authoritative, server-resolved data for one Initiate Sale request. Never derived from unvalidated browser input. */
export interface IciciInitiateSaleTransactionInput {
  merchantTxnNo: string;
  /** Fixed two-decimal string, e.g. "2.00" — the server-authoritative amount, already formatted. */
  amount: string;
  txnDate: string;
  customerEmailID: string;
  customerMobileNo: string;
  customerName: string;
  returnURL: string;
  addlParam1?: string;
  addlParam2?: string;
}

export interface IciciInitiateSaleRequestBody extends IciciDirectOrangeInitiateSaleFields {
  secureHash: string;
}

/**
 * Builds the full JSON request body (fields + secureHash) for the Direct
 * Orange PG Initiate Sale call. `config.hashKey` is used only to compute
 * the hash and is never included in the returned object.
 */
export function buildIciciInitiateSaleRequestBody(
  input: IciciInitiateSaleTransactionInput,
  config: Pick<IciciConfig, 'merchantId' | 'aggregatorId' | 'currencyCode' | 'payType' | 'transactionType' | 'hashKey'>,
): IciciInitiateSaleRequestBody {
  const fields: IciciDirectOrangeInitiateSaleFields = {
    merchantId: config.merchantId,
    aggregatorID: config.aggregatorId,
    merchantTxnNo: input.merchantTxnNo,
    amount: input.amount,
    currencyCode: config.currencyCode,
    payType: config.payType,
    customerEmailID: input.customerEmailID,
    transactionType: config.transactionType,
    returnURL: input.returnURL,
    txnDate: input.txnDate,
    customerMobileNo: input.customerMobileNo,
    customerName: input.customerName,
    // NOTE: empty string is our current, UNCONFIRMED representation for an
    // absent optional param (see crypto.ts module doc, "KNOWN GAPS #2").
    // Revisit if ICICI's UAT response indicates it expects something else.
    addlParam1: input.addlParam1 ?? '',
    addlParam2: input.addlParam2 ?? '',
  };

  const secureHash = generateIciciDirectOrangeInitiateSaleHash(fields, config.hashKey);

  return { ...fields, secureHash };
}
