-- ICICI Orange PG payment transaction ledger.
--
-- Server-side only: this table is written and read exclusively by backend
-- (Vercel serverless) code using the Supabase service-role key. Row Level
-- Security is enabled with NO policies, so the anon/authenticated keys
-- (including the publishable VITE_SUPABASE_ANON_KEY used by the browser)
-- get zero access even by mistake — only the service-role key, which
-- bypasses RLS, can read or write this table. The service-role key must
-- never be set as a VITE_*/NEXT_PUBLIC_*/PUBLIC_* env var and must never
-- reach frontend bundles.
--
-- No card number, CVV, OTP, or other raw payment-instrument data is stored
-- here — only gateway references, amounts, and lifecycle state.

create table if not exists public.payment_transactions (
  id uuid primary key default gen_random_uuid(),

  -- Prezenti-generated merchant transaction number sent to ICICI as
  -- merchantTxnNo. Bank-confirmed constraint: values over 20 characters
  -- suppress QR code generation, so 20 is treated as a hard cap here.
  merchant_txn_no varchar(20) not null,

  -- Gateway identifier, kept explicit so this table can host other
  -- providers later without a schema change.
  provider varchar(30) not null default 'icici_orange_pg',

  -- Bank-side identifiers, populated once known (not present at INITIATED
  -- time). Used as idempotency keys for repeated callbacks.
  provider_transaction_id text,
  provider_payment_id text,

  -- tranCtx returned by Initiate Sale; required to complete the redirect.
  tran_ctx text,

  -- Internal reference this transaction is for (Prezenti's own quote/order
  -- reference — e.g. QuoteDraft.quoteId), independent of any bank ID.
  internal_reference text,

  -- Authoritative amount as determined server-side. NEVER trust a
  -- browser-supplied amount when writing this column.
  amount numeric(12, 2) not null,
  currency varchar(3) not null default '356',

  customer_name text,
  customer_email text,
  customer_mobile text,

  return_url text,
  addl_param1 text,
  addl_param2 text,

  -- Normalized internal lifecycle state (see master integration doc for
  -- the ICICI responseCode -> status mapping once that is confirmed).
  status text not null default 'INITIATED',

  payment_mode text,
  payment_sub_inst_type text,
  response_code text,
  response_description text,
  payment_datetime timestamptz,

  -- Sanitized raw payloads kept for audit/reconciliation. Do not persist
  -- secureHash keys, OTP, CVV, or card data into these blobs.
  raw_initiate_response jsonb,
  raw_callback_payload jsonb,

  -- Idempotency support: count of callbacks processed for this
  -- transaction, and the timestamp of the most recent one, so a repeated
  -- callback can be detected and short-circuited without reapplying
  -- side effects (order fulfillment, notifications, etc).
  callback_received_count integer not null default 0,
  last_callback_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint payment_transactions_status_check check (
    status in ('INITIATED', 'PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', 'EXPIRED', 'UNKNOWN')
  ),
  constraint payment_transactions_amount_positive check (amount > 0),
  constraint payment_transactions_merchant_txn_no_length check (char_length(merchant_txn_no) <= 20)
);

-- Uniqueness / idempotency constraints.
-- merchant_txn_no is generated by Prezenti and must be globally unique.
create unique index if not exists payment_transactions_merchant_txn_no_key
  on public.payment_transactions (merchant_txn_no);

-- provider_transaction_id / provider_payment_id are only known once ICICI assigns
-- them, so uniqueness is enforced only where present (partial indexes),
-- preventing two transactions from ever claiming the same bank-side ID —
-- the core idempotency guard against duplicate callback processing.
create unique index if not exists payment_transactions_provider_transaction_id_key
  on public.payment_transactions (provider_transaction_id)
  where provider_transaction_id is not null;

create unique index if not exists payment_transactions_provider_payment_id_key
  on public.payment_transactions (provider_payment_id)
  where provider_payment_id is not null;

-- Lookup/reconciliation indexes.
create index if not exists payment_transactions_status_idx
  on public.payment_transactions (status);

create index if not exists payment_transactions_internal_reference_idx
  on public.payment_transactions (internal_reference);

create index if not exists payment_transactions_created_at_idx
  on public.payment_transactions (created_at desc);

-- Keep updated_at current on every write.
create or replace function public.set_payment_transactions_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists payment_transactions_set_updated_at on public.payment_transactions;

create trigger payment_transactions_set_updated_at
  before update on public.payment_transactions
  for each row
  execute function public.set_payment_transactions_updated_at();

-- Atomically records receipt of a return/callback for an existing
-- transaction: increments callback_received_count (every call counts,
-- including repeats — idempotency means never creating a new row here,
-- not suppressing the counter), stamps last_callback_at, stores the raw
-- payload for audit, sets status, and (when provided) records the
-- bank-assigned provider identifiers — provider_transaction_id/
-- provider_payment_id carry the actual idempotency-critical unique
-- constraints (see the partial unique indexes above), so a genuinely
-- duplicate callback with the same bank-assigned ID can be detected at
-- the database level, not just by merchant_txn_no. This is an UPDATE
-- only — a repeated callback for the same merchant_txn_no can never
-- create a second transaction row.
--
-- NOTE: this function's signature was extended after its first live
-- deployment (new parameters added with defaults, so existing callers
-- remain valid) — applied via direct SQL through Supabase MCP, per this
-- project's no-migration-tooling policy; this file is a reviewable
-- reference copy, not something any tool runs.
create or replace function public.record_payment_callback(
  p_merchant_txn_no text,
  p_status text,
  p_raw_callback_payload jsonb,
  p_provider_transaction_id text default null,
  p_provider_payment_id text default null,
  p_response_code text default null,
  p_response_description text default null,
  p_payment_mode text default null,
  p_payment_datetime timestamptz default null
) returns void
language plpgsql
as $$
begin
  update public.payment_transactions
  set
    status = p_status,
    raw_callback_payload = p_raw_callback_payload,
    provider_transaction_id = coalesce(p_provider_transaction_id, provider_transaction_id),
    provider_payment_id = coalesce(p_provider_payment_id, provider_payment_id),
    response_code = coalesce(p_response_code, response_code),
    response_description = coalesce(p_response_description, response_description),
    payment_mode = coalesce(p_payment_mode, payment_mode),
    payment_datetime = coalesce(p_payment_datetime, payment_datetime),
    callback_received_count = callback_received_count + 1,
    last_callback_at = now()
  where merchant_txn_no = p_merchant_txn_no;
end;
$$;

-- Server-side only: enable RLS with no policies so anon/authenticated
-- roles have no access path to this table under any circumstance. Only
-- the service-role key (used exclusively in backend/serverless code)
-- bypasses RLS and can read/write here.
alter table public.payment_transactions enable row level security;

comment on table public.payment_transactions is
  'ICICI Orange PG payment transaction ledger. Server-side access only via the Supabase service-role key — RLS is enabled with no policies, so anon/authenticated roles have zero access. Never store card number, CVV, OTP, or the ICICI hash key here.';
